name: Setup EIP
on:
  workflow_dispatch:

jobs:
  allocate-eip:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Run EIP script
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat /tmp/eip_run.log || echo "Not found"
